# Generated by Django 4.0.3 on 2023-01-25 01:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_remove_tweet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(db_index=True, max_length=255, verbose_name='image'),
        ),
    ]
