# Generated by Django 3.2.1 on 2023-01-25 08:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_alter_tweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(db_index=True, max_length=255, verbose_name='image'),
        ),
    ]
